- name: Setup Alarm Clock on Raspberry Pi
  hosts: localhost
  user: '{{ user_name }}'
  become: yes
  vars_files:
    - /vars/vars.yml

  tasks:

  - name: Install docker
    ansible.builtin.package:
      name: docker
      state: present

  - name: Install docker-compose
    ansible.builtin.package:
      name: docker-compose
      state: present

  - name: Install python3 if not already installed
    ansible.builtin.package:
      name: python3
      state: present

  - name: Install pip
    ansible.builtin.package:
      name: pip
      state: present
  
  - name: Install Alarm dependancies - pysimplegui
    ansible.builtin.pip:
      name: pysimplegui

  - name: Install Alarm dependancies - tkinter
    ansible.builtin.pip:
      name: tk

  - name: Install Alarm dependancies - pyglet
    ansible.builtin.pip:
      name: pyglet

  - name: Install Alarm dependancies - pyyaml
    ansible.builtin.pip:
      name: pyyaml

  - name: Install apt tkinter
    ansible.builtin.apt:
      name: python-tk

# Next - Setup python script to start by default

  - name: Pull Alarm Clock files and verify they are in the home dir for user pi
    ansible.builtin.git:
      repo: https://github.com/madeofpendletonwool/pyArmClock.git
      dest: /home/{{ user_name }}/pyArmClockBoot
      clone: yes
      update: yes

  - name: Start Alarm Clock at Boot
    ansible.builtin.cron:
      name: "Boot Python Alarm Clock"
      special_time: reboot
      job: "/home/{{ user_name }}/pyArmClock/alarm.py"